# Generated by Django 2.2.16 on 2022-05-14 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220513_1901'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='uniqueness of cart and user',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='uniqueness of favorite recipe and user',
        ),
        migrations.RemoveConstraint(
            model_name='ingredients',
            name='uniqueness of ingredient and measurement',
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингредиента д.б. 1')], verbose_name='Количество'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='uniqueness of user and foods in cart'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='uniqueness of user and favorite recipes'),
        ),
        migrations.AddConstraint(
            model_name='ingredients',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='uniqueness of food and measurement unit'),
        ),
    ]
