# Generated by Django 2.2.19 on 2022-05-18 10:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220514_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингредиента д.б. 1')], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Количество ингридиента',
                'verbose_name_plural': 'Количество ингридиентов',
                'ordering': ['-id'],
            },
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
        migrations.RemoveConstraint(
            model_name='ingredients',
            name='uniqueness of food and measurement unit',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='measurement_unit',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='recipes.Recipes', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='ingredients',
            constraint=models.UniqueConstraint(fields=('name', 'unit'), name='uniqueness of food and measurement unit'),
        ),
        migrations.AddField(
            model_name='ingredientsquantity',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredients', verbose_name='Ингридиент'),
        ),
        migrations.AddField(
            model_name='ingredientsquantity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipes', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='ingredientsquantity',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='recipe`s ingredient uniqueness'),
        ),
    ]
